# Generated by Django 3.1.6 on 2021-02-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20210224_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupform',
            name='mobileno',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterModelTable(
            name='signupform',
            table='reports',
        ),
    ]
